### ISSUE TITLE
Search .docx content

### ISSUE THREAD

**Issue by Perkin5** [stefankueng/grepWin#463] opened 2024-03-06 14:37 UTC
I have downloaded the latest version of GrepWin but was disappointed to find that, although it will find content in .doc files, it seems unable to find content in .docx files - which is mainly what I want it for. Am I making a mistake or is there a fix?

**Comment by lifenjoiner** [comment] 2024-03-07 00:47
In fact, `.docx` and other Office 2007 format files are zip packages. Unpack them and then search is possible.

I don't think `grepWin` promised supporting either `.doc` or `.docx` files.
As the name implies, it is `grep`. Do you know `grep`? It is targeting text files.

**Comment by stefankueng** [comment] 2024-03-07 05:46
https://github.com/stefankueng/grepWin/issues?q=is%3Aissue+docx
duplicate of #12, #166, #232, #290, #389 and I'm sure a few more.

**Closed as completed by stefankueng** 2024-03-07 05:46 UTC
Labels: duplicate

**Comment by Perkin5** [comment] 2024-03-07 13:32
Sorry, this was not an app useful to me if it only designed to search txt files so I shall uninstall.

**Comment by lifenjoiner** [comment] 2024-03-08 00:50
Come on, man.
Be polite, grateful. Don't be mean.
Disappointed? Does the author own you anything? He offers his work free, even open source!
Not an app useful? It really ruins all contributors emotions.
Uninstall? Is this a threat? It would be great, if I am the author, that won't ruin my passion anymore.

These negative words don't help.
If you don't satisfy with anything, improve it, contribute to the community to make it better, even, you can fork it, or make your brand new one.
At least, treat open source contributors well!

**Comment by lifenjoiner** [comment] 2024-03-08 01:02
I saw open source believers passion consumed and disappointed. That is a tragedy! I don't think you want it.
