### ISSUE TITLE
Can't run x86 variant of 2.0.0 release on Windows7 (neither 32- nor 64-bit)

### ISSUE THREAD

**Issue by ziembla** [stefankueng/grepWin#146] opened 2020-05-21 10:18 UTC
It seems that the x86 version of the tool is somewhat broken as I was able to run it only on 64b Win10 box...
The best way to show the problem will be in tabular form

```
grepwin2.0.0 variant
            x64   x86
Win10 64b   ok   ok
Win7  64b   ok   NO
Win7  32b        NO
```

On 32b box the process starts and shuts down without any windows, on 64b one I got windows process problem window with "problem: BEX" in "module: StackHash_0a9e".

**Comment by stefankueng** [comment] 2020-05-21 11:51
dupe of #143

**Closed as completed by stefankueng** 2020-05-21 11:51 UTC
Labels: duplicate

**Comment by ziembla** [comment] 2020-05-21 15:37
Thanks for the updated version, I've just confirmed it is working on both problematic systems. Sorry for posting duplicate, but I didn't check closed issues for the problem present in the latest release.
These details aside, thanks a lot for a great tool!
