### ISSUE TITLE
LF files cause erroneous extra line matches 

### ISSUE THREAD

**Issue by Brondahl** [stefankueng/grepWin#141] opened 2020-05-05 07:28 UTC
When reading a file with LF line endings, and the search term matches to the end of one of the lines, then the search returns the *next* line as well as the matched line.

This happens both for simple text searches, and also for Regex searches that, e.g. end `.*$` (with `.` not matching new lines.

Switching line-endings of the file to CRLF, or modifying the match to not match the last (non-LF) character of the line prevents the problem.

**Comment by Brondahl** [comment] 2020-05-05 07:29
I'm on version `1.8.0.766`.
Happy to try out the latest version if you think this has been fixed since that version.

**Comment by stefankueng** [comment] 2020-05-05 20:16
please give an example search string and maybe file lines to reproduce the problem.

**Comment by Brondahl** [comment] 2020-05-06 07:25
Certainly, here is one fi..... oh.
Interesting. A first attempt to create a trivial repro has failed.

I'll dig into it further to generate a minimal case.

**Comment by Brondahl** [comment] 2020-05-06 08:42
OK, so I have a file that demonstrates the bug, but it is version dependant, and is fixed in v-latest.

For reference, in case you want to look into what happened anyway ...

In the test file: [GrepWin test file.txt](https://github.com/stefankueng/grepWin/files/4585658/GrepWin.test.file.txt)
- Searching "EndX" ought to return exactly 1 line: Line X
- Searching "End3" or "End4" do both return the correct single lines respectively.
- But searching "End1", "End2", "End5" or !! "End6" !! each return 2 lines - the actual line and (erroneously) the line after.
- Note in the last case, searching "End6" returns 2 lines: line 6, and the **_non-existent_** line 7!

I was able to test against various versions:
- v`1.6.0.466` does NOT have the bug.
- v`1.8.0.766` DOES have the bug.
- v`1.8.1.778` DOES have the bug.
- v`1.9.0.805` DOES have the bug.
- v`1.9.1.819` DOES have the bug.
- v`1.9.2.831` does NOT have the bug.
- v`2.0.0.856` = v`latest` does NOT have the bug.

i.e. this was introduced between `1.6.0` and `1.8.0`, and then fixed in `1.9.2`

**Comment by stefankueng** [comment] 2020-05-06 15:39
thanks for testing all the versions!
So since this is fixed in the latest version, I'm closing this issue.
Feel free to reopen it if necessary.

**Closed as completed by stefankueng** 2020-05-06 15:39 UTC
