### ISSUE TITLE
grepWin_2.0.0.856_32-bit does not start on Windows 7 Pro SP1 32-bit

### ISSUE THREAD

**Issue by hpwamr** [stefankueng/grepWin#145] opened 2020-05-15 21:44 UTC
Hello @stefankueng ,
I've just installed a test Laptop with a pristine Windows 7 Pro SP1 32-bit, to try the Install and Portable version of "grepWin_2.0.0.856_32-bit" in that environment.

Result: **"grepWin_2.0.0.856_32-bit"** does NOT start and run in **Windows 7 Pro SP1 32-bit**. 😬 

If necessary, I can reproduce it and send you event logs. 🤔 

Edit: NO problem with previous version "grepWin_1.9.2.831_32-bit"

**Comment by stefankueng** [comment] 2020-05-16 06:15
dupe of #131

**Closed as completed by stefankueng** 2020-05-16 06:15 UTC
Labels: duplicate
