### ISSUE TITLE
Version 2.1.4 doesn't find folders

### ISSUE THREAD

**Issue by mambax7** [stefankueng/grepWin#501] opened 2024-07-28 06:44 UTC
This issue is back in Version 2.1.4:

https://github.com/stefankueng/grepWin/issues/482

**Comment by hpwamr** [comment] 2024-07-28 14:12
Régression ! 😁 
Version 2.1.4 finds a folder ONLY at the 1st level of folders ?
But **NOT** for a folder of the 2nd level or more ?

Example: Test with the application "**grepWin-main**":
- Search for the folder "**Resources**" from:  **`.\scr`** is OK  👍 
- The same search for the folder "**Resources**" from:  **`.\grepWin-main`** is NOT OK 👎

**Comment by mambax7** [comment] 2024-07-28 20:14
Sadly, that's a **HUGE step backwards** in usability, because in the past it worked wonderfully regardless of how many level it was. I could run it from c:\ and it would ALL files, even 5-7 levels down. 
It might have taken a little bit longer, but I could let it run, go for a lunch, but be confident that when I come back, all the files that I needed will be found! 

For example, I'm using WAMPServer, and in the /www/ folder I have all my websites for local testing. Each website is using many common files, and they could be 5-7 levels down. Now, if I found a bug in a particular function, and I want to find the function across thousands of files in order to fix it in all of them, it was a piece of cake in the past. 
Now you're telling me that it won't be possible anymore! Why? 😢
This was a key feature for me, and a huge time saver. If I have to go now manually through thousands of folders in order to find the files, it will kill me! 
![image](https://github.com/user-attachments/assets/c936a42a-d0fc-45e9-b894-c143db42caca)

**Comment by lifenjoiner** [comment] 2024-07-30 11:09
Steady~, guys!
No body says it won't be fixed.
Besides, there are previous versions working.
We introduced new features and did refactoring/optimization, and will keep it going on. Regressions are not expected, but they do happen. We need time.
Be positive!
If open source does not yield pleasure, where is the energy to keep on contributing?

**Comment by lifenjoiner** [comment] 2024-07-30 11:10
Test the latest dev built artifacts from https://github.com/stefankueng/grepWin/actions?query=branch%3Amain

**Comment by bitzer-sbc** [comment] 2024-07-30 12:01
We appreciate your work, and we will be patient.
I think @mambax7 got it wrong, that this should be an intentional change.
Maybe he should spend the waiting time learning about Git submodules for his shared code instead of doing search and replace across all his projects 😁

**Comment by mambax7** [comment] 2024-07-30 12:35
@bitzer-sbc Don't worry, I'm aware of that 😁

However, I misread the original post from @hpwamr (before his edits):

![image](https://github.com/user-attachments/assets/f86e4a54-e1de-4e03-b44d-bcd2ab909f9d)

as I've mistaken it as a response from @stefankueng, telling me that this is the new behavior going forward. And for that I would like to apologize to @stefankueng.
Lesson learned: I need to pay attention to who actually posted the response to my post.

@lifenjoiner Thanks for looking into it

**Comment by bitzer-sbc** [comment] 2024-07-30 13:14
@lifenjoiner Maybe I was too quick adding my comments to issue 502 (https://github.com/stefankueng/grepWin/issues/502#issuecomment-2257638427)
Is this related to the changes you made, or should I raise a separate issue?

**Comment by lifenjoiner** [comment] 2024-07-30 14:23
> @lifenjoiner Maybe I was too quick adding my comments to issue 502 ([#502 (comment)](https://github.com/stefankueng/grepWin/issues/502#issuecomment-2257638427))
> Is this related to the changes you made, or should I raise a separate issue?

Let's discuss it under your original post. New issue can be raised if necessary.

**Comment by stefankueng** [comment] 2024-08-02 08:00
Sorry for my absence. Was hiking the last few days.
Is this issue still happening for you? I can't reproduce it with the latest build.

**Comment by mambax7** [comment] 2024-08-02 13:51
@stefankueng Nothing to be sorry about - hiking is awesome, and you need it to recharge your batteries! 
on the latest build (https://github.com/stefankueng/grepWin/actions/runs/10179332976) I'm getting 
![image](https://github.com/user-attachments/assets/41ce715a-b95c-4785-a5d0-f005d0c2e8a8)

Here are the details:
`webfile: C:\Download\grepWin-x64.zip|https://productionresultssa0.blob.core.windows.net/actions-results/1d2aa30e-0be1-4ae2-abf6-2441c1d16e62/workflow-job-run-d06252bc-68ad-51d4-3591-93d66f49298d/artifacts/ef39a96e671205b1dd5e3f66e3164c10ccffd37f6f28415d4a4d63098e3664cc.zip?rscd=attachment%3B+filename%3D%22grepWin-x64.zip%22&se=2024-08-02T14%3A02%3A09Z&sig=tkoVDbwq%2FFJBf37ZORil66HIpg4pqcvmQxq3D%2FAvfK8%3D&ske=2024-08-02T23%3A28%3A19Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-02T11%3A28%3A19Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-02T13%3A52%3A04Z&sv=2024-05-04|pid:36276,ProcessStart:133670803308791283`

**Comment by hpwamr** [comment] 2024-08-03 18:55
> Régression ! 😁
> Version 2.1.4 finds a folder ONLY at the 1st level of folders ?

> Is this issue still happening for you? I can't reproduce it with the latest build.

The new version 2.1.5 fixes this issue.
Thanks.  👍

**Closed as completed** 2024-08-03 18:56 UTC

**Comment by mambax7** [comment] 2024-08-05 00:00
Yes, the new version 2.1.5 fixes this issue.
Thank you so much!!! 👍
