### ISSUE TITLE
Include subfolders

### ISSUE THREAD

**Issue by djpedrosa** [stefankueng/grepWin#504] opened 2024-07-30 17:03 UTC
in the last version 2.1.4, the "include subfolders" not work properly.

**Comment by lifenjoiner** [comment] 2024-07-31 00:30
Duplicate of https://github.com/stefankueng/grepWin/issues/501.
Test the latest dev built artifacts from https://github.com/stefankueng/grepWin/actions?query=branch%3Amain.

**Closed as completed by lifenjoiner** 2024-07-31 00:30 UTC
