### ISSUE TITLE
grepWin 2.0.3 is crashing

### ISSUE THREAD

**Issue by cakruege** [stefankueng/grepWin#177] opened 2020-07-16 07:56 UTC
If I grep to a directory of large text files (single filesize > 20 GB, directory ~50 GB).
grepWin is crashing without any notice.

Do you have Debug Builds for getting proper crash logs?

**Comment by stefankueng** [comment] 2020-07-16 17:42
sorry, no debug builds.
you could use [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) to try and get a crash dump.

**Comment by markpahulje** [comment] 2020-08-30 04:12
I get a crash on exit, windows 7.
Problem signature:
  Problem Event Name:	BEX
  Application Name:	grepWin-2.0.3_portable.exe
  Application Version:	2.0.3.926
  Application Timestamp:	5f0c9aaf
  Fault Module Name:	grepWin-2.0.3_portable.exe
  Fault Module Version:	2.0.3.926
  Fault Module Timestamp:	5f0c9aaf
  Exception Offset:	000bac68
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	9858
  Additional Information 2:	98588dd5bd6a0d3cbf35b3090705319c
  Additional Information 3:	a538
  Additional Information 4:	a53850c0e0b44641c92c5e0790c33429

UPDATE - NOW FIXED in 2.0.4.961

**Comment by irwir** [comment] 2020-09-01 12:13
It could be a crash also, but no pop-ups, no records in system Events.
As if the portable executable exited silently.

The task was to perform simple text replacements in files of a specific type - less than 800 files (ANSI, not Unicode); total size of files below 17 MB. One directory, two subdirectories.

Copied the executable to a VirtualBox with Windows 10 20H2; all setting should have been the default ones.
Selected directory for processing, entered file mask, search and replacement strings, then hit Replace. 
Progress bar was active, but all counters stayed at zero. High CPU usage and over 1 GB of memory got hogged; the amount was slowly decreasing.
After a while, without any notification, the application vanished.

**Comment by stefankueng** [comment] 2020-12-12 09:44
closing this issue since I can not reproduce this.
Feel free to create a new issue if you experience crashes with current versions.

**Closed as completed by stefankueng** 2020-12-12 09:44 UTC
