### ISSUE TITLE
Feature Request: Disable Replace Button with Execution Parameter

### ISSUE THREAD

**Issue by te333is** [stefankueng/grepWin#434] opened 2023-11-16 15:18 UTC
Hi Stefan,
First of all thanks - GrepWin is an amazing tool - great job!

On feature that could be useful is an execution parameter to disable the Replace button.

Totally realize it is a user problem (fobia?) but sometimes I have thick fingers and do not want to hit Replace instead of Search ending up with knowledge base messed up.

Hope it makes sense to you.

Cheers,
Sven

**Comment by stefankueng** [comment] 2023-11-30 17:40
dupe of #332 and #235

**Closed as completed by stefankueng** 2023-11-30 17:40 UTC
