### ISSUE TITLE
Color the exact search result

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#247] opened 2021-04-07 08:13 UTC
hello, I am using also another program for REGEX, not just grepWin.

I wonder if is it possible with grepWin to color the exact search result just like in this image:

https://snipboard.io/N4gpPz.jpg

**Comment by stefankueng** [comment] 2021-05-20 17:35
dupe of #83

**Closed as completed by stefankueng** 2021-05-20 17:35 UTC
Labels: duplicate
