### ISSUE TITLE
Add colors to highlight a match in context

### ISSUE THREAD

**Issue by helperman** [stefankueng/grepWin#419] opened 2023-08-08 20:26 UTC
See how Notepad++ shows matches in a context.
It can be done with custom listview control (hope it does not hurt performance).

![00002057](https://github.com/stefankueng/grepWin/assets/8351863/b799ea41-766b-4a6b-83c2-a62cbc82a847)

**Comment by stefankueng** [comment] 2023-08-09 17:49
dupe of #83

**Closed as completed by stefankueng** 2023-08-09 17:49 UTC
Labels: duplicate
