### ISSUE TITLE
v2.1.5 crashes straight away on Windows 7 x86

### ISSUE THREAD

**Issue by michelverhagen** [stefankueng/grepWin#516] opened 2024-10-23 03:25 UTC
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	grepWin.exe
  Application Version:	2.1.5.1378
  Application Timestamp:	66ae07b3
  Fault Module Name:	grepWin.exe
  Fault Module Version:	2.1.5.1378
  Fault Module Timestamp:	66ae07b3
  Exception Code:	40000015
  Exception Offset:	000c3e3f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d4ca
  Additional Information 2:	d4caa396141ebf382ab6d1725dd76253
  Additional Information 3:	f0d8
  Additional Information 4:	f0d87d304777ebb9857b4f880230185f

I know Win7 is old, but I have some legacy projects that only run on Win7. Can I download older releases of grepWin somewhere?

**Comment by stefankueng** [comment] 2024-10-23 14:28
try installing the latest c-runtime:
https://aka.ms/vs/17/release/vc_redist.x86.exe
Win7 does not update the 'system' parts of the runtime automatically via windows update - later windows versions do.

**Comment by michelverhagen** [comment] 2024-10-23 21:11
Hi Stefan,

Thanks for the quick response. I installed the redist package and re-installed v2.1.5 after, but unfortunately grepWin still crashes almost straight away when starting a search. I still had a portable v1.6.12 lying around and that one works fine (but of course no context menu, which makes it a bit hard to use).

Error is the same with v2.1.5:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	grepWin.exe
  Application Version:	2.1.5.1378
  Application Timestamp:	66ae07b3
  Fault Module Name:	grepWin.exe
  Fault Module Version:	2.1.5.1378
  Fault Module Timestamp:	66ae07b3
  Exception Code:	40000015
  Exception Offset:	000c3e3f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d4ca
  Additional Information 2:	d4caa396141ebf382ab6d1725dd76253
  Additional Information 3:	f0d8
  Additional Information 4:	f0d87d304777ebb9857b4f880230185f

**Comment by stefankueng** [comment] 2024-10-24 07:45
please try a fresh build from
https://github.com/stefankueng/grepWin/actions/runs/11306270621
the crash might already be fixed.

if it still crashes, please enable crash dumps and then add the (zipped) dump here:
https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by michelverhagen** [comment] 2024-10-26 23:43
Same problem with the fresh build:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	grepWin.exe
  Application Version:	2.1.5.1510
  Application Timestamp:	670a839d
  Fault Module Name:	grepWin.exe
  Fault Module Version:	2.1.5.1510
  Fault Module Timestamp:	670a839d
  Exception Code:	40000015
  Exception Offset:	000c448f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d4ca
  Additional Information 2:	d4caa396141ebf382ab6d1725dd76253
  Additional Information 3:	1b91
  Additional Information 4:	1b915556e8ced39ca82c2d0c543016c4
```
Full crashdump attached (it's a 7z, rename .zip to .7z, had to use 7z because zip exceeded 30MB which is max for github attachments).
[grepWin.exe.2452.zip](https://github.com/user-attachments/files/17532272/grepWin.exe.2452.zip)

**Comment by stefankueng** [comment] 2024-10-30 06:31
thanks for the crash dump. Problem is I don't have the matching pdbs from the github builds, only from the official releases.
Can you install the latest release again, make it crash and send that dump please?

**Comment by stefankueng** [comment] 2024-11-02 08:54
So I installed Win7 and tried it myself. I can not get grepWin to crash. So I need a lot more info or a crash dump from the last official release:

- what folder are you searching in
- what search string are you using
- what other search options are active

**Comment by michelverhagen** [comment] 2024-11-03 04:19
Very strange that you don't see the crash. Did you install Win7 x64 or x86? Mine is 32 bit x86, fresh install in a Virtualbox VM. On top of Win7 I fully updated the OS (which is a mission, but with help from [this tool](https://archive.org/details/wurt_20240121) it works. Then I installed Visual Studio 2005 and Windows CE 6.0 (yes, I know... ;)).

I installed the latest official grepWin release v2.1.5 and searched the Windows folder for "whatever". It doesn't matter which folder I search; it always crashes immediately.
<img width="737" alt="Screenshot 2024-11-03 170856" src="https://github.com/user-attachments/assets/79ed5b38-466a-475c-a3a0-7d844fb3d2d7">

Here's the crash dump (same story, rename .zip to .7z and decompress with 7-zip):
[grepWin.exe.3588.zip](https://github.com/user-attachments/files/17609285/grepWin.exe.3588.zip)

**Comment by stefankueng** [comment] 2024-11-03 11:32
Thanks for the crash dump. It shows that hundreds of threads are created for the search.
I committed a fix, but since I can not reproduce the problem myself, can you download the fixed version from [here](https://github.com/stefankueng/grepWin/actions/runs/11650941514) and check if the problem is fixed for you?

**Comment by michelverhagen** [comment] 2024-11-03 12:07
Yes, all working perfectly now! Thanks!!!

**Comment by stefankueng** [comment] 2024-11-04 17:52
thanks for testing!

**Closed as completed by stefankueng** 2024-11-04 17:52 UTC
Labels: bug
