### ISSUE TITLE
Portable x32 does not apply settings and does not see the language file on x64 OS

### ISSUE THREAD

**Issue by wvxwxvw** [stefankueng/grepWin#126] opened 2020-04-07 20:00 UTC
Try to change something yourself in the settings and apply it.
The language string is empty.
OS Win7x64

**Comment by stefankueng** [comment] 2020-04-08 18:08
works fine for me.
Are you trying the "dark mode" setting? That won't work on Win7.

**Comment by wvxwxvw** [comment] 2020-04-09 07:37
It is clear about the dark mode, but the settings do not work at all.

**Comment by stefankueng** [comment] 2020-04-09 07:53
I can change any setting in portable mode and it works.
About the language string being empty: do you mean the combobox where you select the languages? That's populated by scanning the dir where grepWin.exe lies for *.lang files.

**Comment by wvxwxvw** [comment] 2020-04-09 08:02
No. This is filled in in any case English.lang. But do you think I haven't put my language file down and am trying to achieve something without it?

**Comment by stefankueng** [comment] 2020-04-09 08:08
please don't get upset, I'm trying here!
As I said it works fine for me so I'm trying to figure out why it doesn't work for you. So any info you can give me about your setup can help.

please attach a screenshot of the settings dialog showing the empty language string.
what path do you have grepwin_portable.exe in? Or do you start grepwin.exe with the `/portable` parameter?
what other files are in the same dir as the grepwin exe?

**Comment by wvxwxvw** [comment] 2020-04-09 08:22
No files there. At all. I don’t even put the “language”. Whatever I change in the settings dialog, nothing is applied, the OK button doesn't work. Settings are not changed and upon exit, an empty grepwin.ini is created.

The dialog itself doesn't work. You need to check the file on Windows 7 x64.

**Comment by wvxwxvw** [comment] 2020-04-09 08:36
![111-anim](https://user-images.githubusercontent.com/13194155/78875313-5c262000-7a56-11ea-82fc-eb00d11a67ac.gif)

**Comment by stefankueng** [comment] 2020-04-09 09:16
Well, I don't have a win7 machine available to test.
Also: even your "size" combobox is empty. Which means there's something seriously wrong here.
Try removing the Russian.lang file and try without that.

**Comment by wvxwxvw** [comment] 2020-04-09 09:25
I tried everything, both from different folders and resetting attributes. The problem is in the code, not in the folders/files.

**Comment by wvxwxvw** [comment] 2020-04-09 09:30
I found something. I'm going to record a gif.

**Comment by wvxwxvw** [comment] 2020-04-09 09:42
No, nothing to record.

In the x32 file, even the "about" link does not work.

Try downloading your file from here and check it again. Somehow it is hard to believe that such a glitch depends on the OS.

**Comment by stefankueng** [comment] 2020-04-09 09:51
I did, and the checksums match the files I got here.
Try disabling your virus scanner or set an exception for grepWin. In my experience most "unexplainable" problems are caused by those...

**Comment by stefankueng** [comment] 2020-04-09 10:41
one more thing you should check: in explorer, right-click on the grepwin exe, then go to "properties".
in the properties dialog, look for a tab "digital signature" and check if it's valid.
if you don't see that tab, then the exe is corrupted (or not from me).

**Comment by wvxwxvw** [comment] 2020-04-09 13:00
Kindergarten.

**Comment by stefankueng** [comment] 2020-04-09 18:54
Since you can't provide information without adding insults I'm closing this issue.

Maybe next time remember that I'm doing all this for free. And also remember that if I can't reproduce the problem that I then need information from you, and that I can't know what you already tried if you don't mention that. If I'm asking questions, there's a reason for that. If you don't want to answer my questions, then just say so and go away - no need to insult me.
Also remember that if when I invest a lot of time to try and reproduce your problem but everything works fine on my side, it has to be something on your side that is different than what I have on my side here. If you find that offensive, then just go away.

**Closed as completed by stefankueng** 2020-04-09 18:54 UTC

**Comment by wvxwxvw** [comment] 2020-04-10 09:43
To suggest that I turn off the antivirus (which I don’t have) and assume that the file I downloaded was not from here - this is not a search for a solution. This is the level of advice from stupid forums where some noobs write something to others and give advice at that level. Those. Kindergarten.

Do you really think that antivirus can block the program so that it will run, but not completely!? lol

You don’t have Windows 7 - well, go and find it to check, but don’t make silly assumptions about something wrong with my pc.

Correctly done that closed the thread.

**Comment by stefankueng** [comment] 2020-04-10 09:47
On 10.04.2020 11:43, wvxwxvw wrote:
> To suggest that I turn off the antivirus (which I don’t have) and assume 

How could I know that you don't have an antivirus? You never said

> that the file I downloaded was not from here - this is not a search for 

not "not frome here" but corrupted during download - happens more often 
than you think.

> a solution. This is the level of advice from stupid forums where some 
> noobs write something to others and give advice at that level. Those. 
> Kindergarten.

exactly how you behave.


> Do you really think that antivirus can block the program so that it will 
> run, but not completely!? lol

yes. And I've seen that many, many, many times.

> 
> You don’t have Windows 7 - well, go and find it to check, but don’t make 
> silly assumptions about something wrong with my pc.

better idea: go and get Win10 since Win7 is out of support.
